### PR TITLE
Bug fixes for Property objects assigned to elements

### LINKED ISSUE #182: FEMesh cannot be pushed without a Material assigned to the SurfaceProperty
#### Description:

`FEMesh` cannot be pushed without a `Material `assigned to the `SurfaceProperty`, and likely without a `SurfaceProperty`. 

Error occurs in `FromFEMesh.cs`.

#### Steps to reproduce:

Push FEMesh without SurfaceProperty, or without Material.

#### Expected behaviour:

Push FEMEsh without either properties being required.

### LINKED ISSUE #184: DOF Constraint cannot be pushed to Midas and is assumed as an unassigned free support
#### Description:

`Constraint6DOF` cannot be pushed to Midas. All constraints input in BHoM return with a warning "Unsupported DOFType in "name" assumed to beFree"

#### Steps to reproduce:

-Push a node with support constraint to Midas. 
-A warning will appear in the push component

#### Expected behaviour:

Support with `Constraint6DOF` can be pushed as intended and assigned to the correct nodes.

### LINKED ISSUE #186: Cannot push/pull Constraint6DOF with Springs on 8.8.5
#### Description:

There's a bug when reading `Constraint6DOF `that are MidasCivil springs.

In the transition from 8.8.1 to 8.8.5 the name field moved as shown in https://github.com/BuroHappoldEngineering/MidasCivil_Toolkit/issues/143

The error comes from `ToConstraint6DOF.cs` where 

`                            supportName = delimitted[15].Trim();`

is applied for all cases in the switch statement. That is only valid for the default (i.e. versions prior to 8.8.5) and should be 

`                            supportName = delimitted[21].Trim();`

for 8.8.5.

#### Steps to reproduce:

1. Push a `Node `that has a `Constraint6DOF `assigned
2. As the `Node `is pushed it will read the `Constraint6DOF `and return an error because the name field for springs is incorrect.

#### Expected behaviour:

Push/Pull Constraint6DOF with spring stiffnesses.

### PR DESCRIPTION
**Pull request by StephennipBH**
### Issues addressed by this PR

Closes #182
Closes #184 
Closes  #186 

- Fixed bug where `FEmesh `could not be pushed without a `Material` or a `SurfaceProperty` assigned
- Fixed bug where `Constraint6DOF` was not pushing correctly

### Test files

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FMidasCivil%5FToolkit%2FMidasCivil%5Ftoolkit%2D%23182

### Changelog

- Fixed bug where `FEmesh `could not be pushed without a `Material` or a `SurfaceProperty` assigned
- Fixed bug where `Constraint6DOF` was not pushing correctly
- Fixed bug where `Constraint6DOF` with spring stiffnesses were not read correctly on 8.8.5

### CODE REVIEW

File: MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs [hunk 1]
```diff
@@ -32,7 +32,7 @@ public static Constraint6DOF ToConstraint6DOF(this string support, string versio
         {
             List<string> delimitted = support.Split(',').ToList();
             string supportName;
-
+            string support1;
```
Comment (peterjamesnugent) [inline MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs]: This string is not required, please remove.

File: MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs [hunk 2]
```diff
@@ -94,6 +94,7 @@ public static Constraint6DOF ToConstraint6DOF(this string support, string versio
                                     }
                                 }
                             }
+                        support1 = delimitted[15].Trim();
```
Comment (peterjamesnugent) [inline MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs]: `supportName = delimitted[21].Trim(); `
For version = 8.8.5 the name field index is 21.

Make sure you check the formatting of the code, as it appears to be outside your `case `statement.

File: MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs [hunk 3]
```diff
@@ -119,10 +120,11 @@ public static Constraint6DOF ToConstraint6DOF(this string support, string versio
                                     }
                                 }
                             }
+                            support1 = delimitted[21].Trim();
```
Comment (peterjamesnugent) [inline MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs]: `supportName = delimitted[15].Trim(); `
For version = 8.8.1 or prior the name field index is 15.

File: MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs [hunk 4]
```diff
@@ -119,10 +120,11 @@ public static Constraint6DOF ToConstraint6DOF(this string support, string versio
...
                             break;
                     }
-
-                    supportName = delimitted[15].Trim();
+                    supportName = support1;
```
Comment (peterjamesnugent) [inline MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs]: This line can be removed.
