### PR TITLE
Fixed bug where sections created in MidasCivil would be incorrectly assigned a corbel width

### LINKED ISSUE #304: Error when trying to pull Midas_Created symmetrical sections
#### Description:

When Midas user has 0 as inputs for symmetrical section properties. It would cause an error when trying to pull to the BhoM. This applies to `channelSection`, `iSection` and `boxSection`.

image

#### Steps to reproduce:

Pulling symmetric section created in Midas. (see test script in PR)

### PR DESCRIPTION
**Pull request by StephennipBH**
### Issues addressed by this PR

Closes #304 

This PR would address the issue with error caused by pulling Midas_Created symmetrical section properties. The changes have been made on `ChannelSection`, `ISection` and `BoxSection`.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23304-Corbel%20width%20bug%20on%20box%20sections?csf=1&web=1&e=0zpZXx

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by AntigoniChatzidaki — DISMISSED** [review]
Tested using MidasCivil 2020 v3.2 using the test script. 
Symmetrical section properties were correct.

_Notes:_
For I-sections, the fillet and toe radii are not supported. 
For Channel sections, asymmetrical sections are not supported.

File: MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs [hunk 1]
```diff
@@ -45,19 +45,27 @@ public static IProfile ToProfile(List<string> sectionProfile, string shape, stri
                     double webSpacing = System.Convert.ToDouble(sectionProfile[4]).LengthToSI(lengthUnit);
                     double webThickness = System.Convert.ToDouble(sectionProfile[2]).LengthToSI(lengthUnit);
                     double corbel;
-                    if (System.Math.Abs(width / 2 - webSpacing / 2 - webThickness / 2) < oM.Geometry.Tolerance.Distance)
+                    if (webSpacing < oM.Geometry.Tolerance.Distance)
+                    {
+                        corbel = (width / 2 - webThickness / 2).LengthToSI(lengthUnit);
+                    }
+                    else if (System.Math.Abs(width / 2 - webSpacing / 2 - webThickness / 2) < oM.Geometry.Tolerance.Distance)
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs:52]:
```suggestion
                    if (webSpacing < oM.Geometry.Tolerance.Distance || System.Math.Abs(width / 2 - webSpacing / 2 - webThickness / 2) < oM.Geometry.Tolerance.Distance)
                        corbel = 0;
```
- If the web spacing is 0 in MidasCivil - then there are no corbels. See the comparison between the MidasCivil section and the BHoM section below. As it stands it is still assigning corbels where they do not belong.
- Lack of brackets is style choice, but if you remove them, do it for the `else if` statement below too please.


image
image

File: MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs [hunk 2]
```diff
@@ -81,6 +100,10 @@ public static IProfile ToProfile(List<string> sectionProfile, string shape, stri
                         0, 0);
                     break;
                 case "C":
+                    if (System.Convert.ToDouble(sectionProfile[4]).LengthToSI(lengthUnit) > oM.Geometry.Tolerance.Distance || System.Convert.ToDouble(sectionProfile[5]).LengthToSI(lengthUnit) > oM.Geometry.Tolerance.Distance)
+                    {
+                        Engine.Reflection.Compute.RecordWarning("Asymmetric channel sections are not yet supported in the BHoM_Engine");
+                    }
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs:106]: I am not sure this captures all the possible scenarios for the `Channel` sections. There's a few things we need to check:
- Where B1 = B2  or TF1 = TF2 if both of these are true then create the section
- Otherwise you need to check if B2 < Tolerance and TF2 < tolerance, in which case we can assume B1 = B2 and TF1 = TF2
- Else, the section is asymmetric and cannot be created

File: MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs [hunk 3]
```diff
@@ -69,10 +77,21 @@ public static IProfile ToProfile(List<string> sectionProfile, string shape, stri
...
+                    {
+                        botFlangeThickness = System.Convert.ToDouble(sectionProfile[3]).LengthToSI(lengthUnit);
+                    }
+
                     bhomProfile = Engine.Spatial.Create.FabricatedISectionProfile(
                         System.Convert.ToDouble(sectionProfile[0]).LengthToSI(lengthUnit), System.Convert.ToDouble(sectionProfile[1]).LengthToSI(lengthUnit),
-                        System.Convert.ToDouble(sectionProfile[4]).LengthToSI(lengthUnit), System.Convert.ToDouble(sectionProfile[2]).LengthToSI(lengthUnit),
-                        System.Convert.ToDouble(sectionProfile[3]).LengthToSI(lengthUnit), System.Convert.ToDouble(sectionProfile[5]).LengthToSI(lengthUnit), 0);
+                         botFlangeWidth, System.Convert.ToDouble(sectionProfile[2]).LengthToSI(lengthUnit),
+                        System.Convert.ToDouble(sectionProfile[3]).LengthToSI(lengthUnit), botFlangeThickness, 0);
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs:94]: I think it would be better at the start to just do all the converts for the parameters, that way when you can sau
`botFlangeWidth = topFlangeWidth;`
Which is much clearer than some indexed `string`.

File: MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs [hunk 4]
```diff
@@ -45,19 +45,27 @@ public static IProfile ToProfile(List<string> sectionProfile, string shape, stri
...
-
                     else
                     {
                         corbel = (width / 2 - webSpacing / 2 - webThickness / 2).LengthToSI(lengthUnit);
                     }
+                    double bottomFlangeThickness = System.Convert.ToDouble(sectionProfile[5]).LengthToSI(lengthUnit);
+                    if (bottomFlangeThickness < oM.Geometry.Tolerance.Distance)
+                    {
+                        bottomFlangeThickness = System.Convert.ToDouble(sectionProfile[3]).LengthToSI(lengthUnit);
+                    }
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs:64]: See comment below about storing `topFlangeThickness` so can assign the value to `bottomFlangeThickness below.

Also, be consistent with `bottomFlangeThickness` - below you use botFlangeThickness`.

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
There's a few scenarios that need to be captured - I've added these to the model file and stripped out anything unnecessary. 

Also, I've moved the test files to new folder (you've been saving in the archive).

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by AntigoniChatzidaki — APPROVED** [review]
Tested using MidasCivil 2020 v3.2, using the test files. Works as expected.

When topFlangeWidth is not equal to bottomFlangeWidth, there is a warning that "Asymmetric channel sections are not yet supported by the BHoM. The top flange will be used for the profile." instead of "Asymmetric channel sections are not yet supported by the BHoM. The top flange _width_ will be used for the profile."

**Review by AntigoniChatzidaki — APPROVED** [review]
The warning is corrected.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge
