### PR TITLE
Fix beta-compliance-checks

### LINKED ISSUE #377: Fix code beta-compliance-checks
#### Broken rules:

https://github.com/BHoM/MidasCivil_Toolkit/pull/374/checks?check_run_id=22829587691

#### Suggestions to restore compliance:

Fix errors

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #377 

### Test files

By inspection/compliance check

### Changelog

- Added input parameters for `Create.Metadata` method;
- Added `ToBeRemoved` attribute to `PanelToFEMesh` convert method (that has long since been replaced in the Structure_Engine
- Fixed other beta-documentation-check failures

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check beta-compliance-checks

**Comment by peterjamesnugent** [comment]
@BHoMBot check beta-documentation-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance
@BHoMBot check required

File: MidasCivil_Engine/Compute/FEMeshToPanel.cs [hunk 1]
```diff
@@ -35,6 +36,7 @@ public static partial class Compute
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [ToBeRemoved("4.2","Method was replaced in 4.2 by BH.Engine.Structure.Convert.FEMeshToPanel.")]
```
Comment (FraserGreenroyd) [inline MidasCivil_Engine/Compute/FEMeshToPanel.cs:39]: Can we raise an issue to remove and version in next milestone to avoid being forgotten until 2030? 😄

**Review by FraserGreenroyd — APPROVED** [review]
Happy with changes, one comment on raising issue for future work but otherwise looks good, thanks @peterjamesnugent

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
