### PR TITLE
Push a mesh with more than one face

### LINKED ISSUE #254: FEMesh objects not pushing to MidasCivil despite having only 4 nodes
#### Description:

Unable to push a collection of `FEMesh`.

#### Steps to reproduce:

Create `FEMesh`, Push to Midas

#### Expected behaviour:

`FEMesh` to be pushed successfully to midas.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23254-Push_Mesh_to_MIdas?csf=1&web=1&e=qwLGjN

Setup as shown below
Setup

### PR DESCRIPTION
**Pull request by calumlockhart-bh**
### Issues addressed by this PR

Closes #254 

Allows for `FEMeshes` with more than one `Face` to be pushed into MidasCivil.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23254-Push_Mesh_to_MIdas?csf=1&web=1&e=qwLGjN

### CODE REVIEW

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs [hunk 1]
```diff
@@ -34,10 +37,12 @@ public static partial class Convert
 
         public static string FromFEMesh(this FEMesh feMesh)
         {
-            string midasElement = "";
+        int i = NextFreeId(typeof(FEMesh));
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs:40]: `NextFreeId` stops it from being built, as discussed perhaps just make a `private` method with the following to work out the next available `id`:
```
                    string section = "ELEMENT";

                    if (ExistsSection(section))
                    {
                        index = GetMaxId(section) + 1;
                    }
                    else
                    {
                        index = 1;
                    }
```

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs [hunk 2]
```diff
@@ -48,29 +53,70 @@ public static string FromFEMesh(this FEMesh feMesh)
...
+                    }
+                    discreteMesh.Faces.Add(disFace);
+
+                    discreteMesh.Property = feMesh.Property;
+                    discreteMesh.Property.Material = feMesh.Property.Material;
+                    
+
+                    discreteMesh.SetAdapterId<string>(typeof(MidasCivilId), j);
+                    midasElement += "\n" + FromFEMesh(discreteMesh);
+                    i++;
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs:117]: Rather than rebuild each `Face` as a new `FEMesh` I think we can just make the entire loop from L57 to loop over each `Face` in the `FEMesh` and carry out L59-L81 creating an ELEMENT in MidasCivil.

Then all we need to do is add the method to work out the appropriate id (see comment above).

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
Good start, I think we can consolidate the code a little - see comments.

**Review by StephennipBH — CHANGES_REQUESTED** [review]
I have issues with your `nextFreeID` not being referenced to the correct location which prevents it from being build.

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs (hunk 2 above)
Comment (calumlockhart-bh) [reply MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs]: Changes made

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs (hunk 1 above)
Comment (calumlockhart-bh) [reply MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs]: everything in the MidasCivilAdapter name space is protected so cant use either of these functions in this space, however I have modified the code to get it to work. Please review the changes in both namespaces.

File: MidasCivil_Adapter/CRUD/Create/Elements/Element.cs [hunk 3]
```diff
@@ -74,7 +74,7 @@ private bool CreateCollection(IEnumerable<FEMesh> meshes)
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/CRUD/Create/Elements/Element.cs:74]: We can determine the `index` outside of the `foreach` loop and then pass it by `ref` to reduce the amount of times the text file is read.

`            int index = System.Convert.ToInt32(NextFreeId(typeof(FEMesh)));`

File: MidasCivil_Adapter/CRUD/Create/Elements/Element.cs [hunk 4]
```diff
@@ -74,7 +74,7 @@ private bool CreateCollection(IEnumerable<FEMesh> meshes)
 
             foreach (FEMesh mesh in meshes)
             {
-                midasElements.Add(Adapters.MidasCivil.Convert.FromFEMesh(mesh));
+                midasElements.Add(Adapters.MidasCivil.Convert.FromFEMesh(mesh, System.Convert.ToInt32(NextFreeId(typeof(FEMesh)))));
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/CRUD/Create/Elements/Element.cs:77]:
```suggestion
                midasElements.Add(Adapters.MidasCivil.Convert.FromFEMesh(mesh, ref index));
```

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs [hunk 5]
```diff
@@ -24,18 +24,24 @@
...
 namespace BH.Adapter.Adapters.MidasCivil
 {
     public static partial class Convert
     {
         /***************************************************/
         /**** Public Methods                            ****/
         /***************************************************/
-
-        public static string FromFEMesh(this FEMesh feMesh)
+        private static int index = 0;
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs:39]: Remove this variable as this will not work when we push to a model with existing elements - see changes to `Create` method for `FEMesh`.

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs [hunk 6]
```diff
@@ -24,18 +24,24 @@
...
+        public static string FromFEMesh(this FEMesh feMesh, int index_ = 1)
         {
+            index = Math.Max(index, index_);
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs:42]: Remove, no longer needed see above.

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs [hunk 7]
```diff
@@ -48,31 +54,44 @@ public static string FromFEMesh(this FEMesh feMesh)
...
-             feMesh.Nodes[nodeIndices[0]].AdapterId<string>(typeof(MidasCivilId)) + "," +
-             feMesh.Nodes[nodeIndices[1]].AdapterId<string>(typeof(MidasCivilId)) + "," +
-             feMesh.Nodes[nodeIndices[2]].AdapterId<string>(typeof(MidasCivilId)) + ",0,1,0");
+                int node0 = meshFace.NodeListIndices[0];
+                int node1 = meshFace.NodeListIndices[1];
+                int node2 = meshFace.NodeListIndices[2];
+
+                if (meshFace.NodeListIndices.Count < 3)
+                {
+                    BH.Engine.Reflection.Compute.RecordError("Cannot push mesh with less than 3 nodes");
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs:66]:
```suggestion
                    BH.Engine.Reflection.Compute.RecordError("Cannot push a FEMesh with less than three nodes.");
```

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs [hunk 8]
```diff
@@ -24,18 +24,24 @@
...
 {
     public static partial class Convert
     {
         /***************************************************/
         /**** Public Methods                            ****/
         /***************************************************/
-
-        public static string FromFEMesh(this FEMesh feMesh)
+        private static int index = 0;
+        public static string FromFEMesh(this FEMesh feMesh, int index_ = 1)
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs:40]:
```suggestion
        public static string FromFEMesh(this FEMesh feMesh, ref int index)
```

As above.

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs [hunk 9]
```diff
@@ -24,18 +24,24 @@
...
         {
+            index = Math.Max(index, index_);
+            StringBuilder midasElements = new StringBuilder();
             string midasElement = "";
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs:44]: This can be initialised within the `foreach` loop now that you're using the `StringBuilder`.

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs [hunk 10]
```diff
@@ -48,31 +54,44 @@ public static string FromFEMesh(this FEMesh feMesh)
...
+                else if (meshFace.NodeListIndices.Count == 3)
+                {
+                    midasElement = (index + ",PLATE," +
+                    materialId + "," +
+                    sectionPropertyId + "," +
+                    feMesh.Nodes[node0].AdapterId<string>(typeof(MidasCivilId)) + "," +
+                    feMesh.Nodes[node1].AdapterId<string>(typeof(MidasCivilId)) + "," +
+                    feMesh.Nodes[node2].AdapterId<string>(typeof(MidasCivilId)) + ",0,1,0");
+                }
+
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs:89]:
```suggestion
                meshFace.SetAdapterId(typeof(MidasCivilId), index);
```

Can we add this in to make sure that the `AdapterId` is correct on the BHoM object.

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
I've suggested some changes mainly:
- `NextFreeId` is used at the `Create` level - this avoids all the issues with access in the `Convert` class
- This will work for pushing to empty models, and models with existing ELEMENTS
- We need to assign an `AdapterId` to the `Face` 
- We need to make some changes to how Groups are created, to make sure the `Face` is assigned to the same Groups as the `FEMesh` (see link below)

https://github.com/BHoM/MidasCivil_Toolkit/blob/221d78196a62bf60d9d5f6c759e6897f7f61e79b/MidasCivil_Adapter/PrivateHelpers/CreateGroups.cs#L238-L260

File: MidasCivil_Adapter/CRUD/Create/Elements/Element.cs [hunk 11]
```diff
@@ -72,9 +72,11 @@ private bool CreateCollection(IEnumerable<FEMesh> meshes)
 
             CreateGroups(meshes);
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/CRUD/Create/Elements/Element.cs:73]: Can you move the the `CreateGroups` method until after the `Convert.FEMesh` is called - this is because we need to assign the `Face` `AdapterIds` before creating groups.

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
Works well, I've tested with our generic test script too and those push with no issue.

Can you go through the files you've edited and do the following:
1. CTRL+A (select all)
2. CTRL + K + D 
This will format the code.

Also, can you address this comment (just changing the text on a warning): https://github.com/BHoM/MidasCivil_Toolkit/pull/293/files#r611537633

As for the changes to `CreateGroups` you need to modify the code here:
https://github.com/BHoM/MidasCivil_Toolkit/blob/221d78196a62bf60d9d5f6c759e6897f7f61e79b/MidasCivil_Adapter/PrivateHelpers/CreateGroups.cs#L238-L260

And replace it with
```
                foreach (string tag in mesh.Tags)
                {
                    if (!groupsToAdd.ContainsKey(tag))
                    {
                        StringBuilder meshTags = new StringBuilder(mesh.AdapterId<string>(typeof(MidasCivilId)));
                        foreach(FEMeshFace feMeshFace in mesh.Faces)
                        {
                            meshTags.Append(" " + feMeshFace.AdapterId<string>(typeof(MidasCivilId)));
                        }

                        groupsToAdd.Add(tag, meshTags.ToString());
                    }
                    else
                    {
                        string assignedFEMesh;
                        groupsToAdd.TryGetValue(tag, out assignedFEMesh);
                        string meshId = mesh.AdapterId<string>(typeof(MidasCivilId));

                        StringBuilder assignedIds = new StringBuilder(assignedFEMesh);

                        if (!assignedFEMesh.Contains(meshId))
                        {
                            assignedIds.Append(" " + meshId);
                        }

                        foreach(FEMeshFace feMeshFace in mesh.Faces)
                        {
                            string faceId = feMeshFace.AdapterId<string>(typeof(MidasCivilId));
                            if (!assignedFEMesh.Contains(faceId))
                            {
                                assignedIds.Append(" " + faceId);
                            }
                        }

                        groupsToAdd[tag] = assignedFEMesh;
                    }
                }
```

I've tested that change and it works as expected, but feel free to carry out your own tests.

**Comment by calumlockhart-bh** [comment]
> Works well, I've tested with our generic test script too and those push with no issue.
> 
> Can you go through the files you've edited and do the following:
> 
> 1. CTRL+A (select all)
> 2. CTRL + K + D
>    This will format the code.
> 
> Also, can you address this comment (just changing the text on a warning): https://github.com/BHoM/MidasCivil_Toolkit/pull/293/files#r611537633
> 
> As for the changes to `CreateGroups` you need to modify the code here:
> https://github.com/BHoM/MidasCivil_Toolkit/blob/221d78196a62bf60d9d5f6c759e6897f7f61e79b/MidasCivil_Adapter/PrivateHelpers/CreateGroups.cs#L238-L260
> 
> And replace it with
> 
> ```
>                 foreach (string tag in mesh.Tags)
>                 {
>                     if (!groupsToAdd.ContainsKey(tag))
>                     {
>                         StringBuilder meshTags = new StringBuilder(mesh.AdapterId<string>(typeof(MidasCivilId)));
>                         foreach(FEMeshFace feMeshFace in mesh.Faces)
>                         {
>                             meshTags.Append(" " + feMeshFace.AdapterId<string>(typeof(MidasCivilId)));
>                         }
> 
>                         groupsToAdd.Add(tag, meshTags.ToString());
>                     }
>                     else
>                     {
>                         string assignedFEMesh;
>                         groupsToAdd.TryGetValue(tag, out assignedFEMesh);
>                         string meshId = mesh.AdapterId<string>(typeof(MidasCivilId));
> 
>                         StringBuilder assignedIds = new StringBuilder(assignedFEMesh);
> 
>                         if (!assignedFEMesh.Contains(meshId))
>                         {
>                             assignedIds.Append(" " + meshId);
>                         }
> 
>                         foreach(FEMeshFace feMeshFace in mesh.Faces)
>                         {
>                             string faceId = feMeshFace.AdapterId<string>(typeof(MidasCivilId));
>                             if (!assignedFEMesh.Contains(faceId))
>                             {
>                                 assignedIds.Append(" " + faceId);
>                             }
>                         }
> 
>                         groupsToAdd[tag] = assignedFEMesh;
>                     }
>                 }
> ```
> 
> I've tested that change and it works as expected, but feel free to carry out your own tests.

I understand what this does, but I would question if its something we want to do. Having a unique tag for each mesh face makes sense, but arguably having a single tag to represent the entire mesh makes more sense for referencing?

**Comment by peterjamesnugent** [comment]
@calumlockhart-bh all this is doing is taking whatever tags are applied to the `FEMesh` object and making sure the `FEMeshFaces` are also assigned to those same groups.

For example, I have a single `FEMesh` with 100 `FEMeshFaces`. The `FEMesh` has the tags: "Panel", "Steel", "Cast 1" and "Horizontal". When I push those in to MidasCivil, I am going to get 100 PANEL elements and I want them to be included in the same groups.

The alternative is have 1000 `FEMesh` objects with 1 `FEMeshFace` each. Instead of making sure the `FEMeshFaces` are included in the groups, you make a group that relates the `FEMeshFace` to the `FEMesh` with an group that contains it's Id or something. For a high number of `FEMesh` this becomes unmanageable.

File: MidasCivil_Adapter/PrivateHelpers/CreateGroups.cs [hunk 12]
```diff
@@ -237,26 +238,44 @@ private void CreateGroups(IEnumerable<FEMesh> meshes)
...
+                        foreach(FEMeshFace feMeshFace in mesh.Faces)
+                        {
+                            string faceId = feMeshFace.AdapterId<string>(typeof(MidasCivilId));
+                            if (!assignedFEMesh.Contains(faceId))
+                            {
+                                assignedIds.Append(" " + faceId);
+                            }
                         }
 
                         groupsToAdd[tag] = assignedFEMesh;
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/PrivateHelpers/CreateGroups.cs:275]:
```suggestion
                        groupsToAdd[tag] = assignedIds.ToString();
```

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
Updated the test script to account for different tags, recurring tags, different `MaterialFragments` and `SurfaceProperty` objects.

Only one change to be made highlighted, once that's updated I'm happy to merge.

**Review by peterjamesnugent — APPROVED** [review]
LGTM.

**Comment by peterjamesnugent** [comment]
@BHoMBot check all

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Comment by peterjamesnugent** [comment]
@BHoMBot check core

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Comment by peterjamesnugent** [comment]
@BHoMBot check-installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

**Comment by peterjamesnugent** [comment]
@BHoMBot check serialisation

**Comment by peterjamesnugent** [comment]
@BHoMBot check versioning
