### PR TITLE
Fix bugs related to the upgrade to MidasCivil_NX

### LINKED ISSUE #398: Fix bug for importing AreaUniformlyDistributedLoad
#### Description:

`AreaUniformlyDistributedLoad` does not import to MidasCivil_NX.

#### Steps to reproduce:

Try to import pushed `AreaUniformlyDistributedLoad`

### PR DESCRIPTION
**Pull request by EmmaSander**
### Issues addressed by this PR

Closes #398 

As a new Midas Civil version was added to use the new API feature the old versioning for 9.5.0 was lost, this adds version 9.5.0.nx where it is needed to create a mct file with the right format.

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/MidasCivil_Toolkit/%23401-AddMidasCivilNXversioning/BuroHappold_BHoM_v8.0.beta_Create%20read%20loads%20(1).gh?csf=1&web=1&e=NgCEyd 

### Changelog
- Fixed a bug in NX where `AreaUniformlyDistributedLoad` and `PointForce` were not been parsed in Midas;
- Fixed a bug in NX where `RigidLink` was not being parsed in Midas;
- Fixed a bug in where `LoadCombination` was not being parsed in Midas;

### CODE REVIEW

File: MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromRigidLink.cs [hunk 1]
```diff
@@ -58,6 +58,7 @@ public static string FromRigidLink(this RigidLink link, string version)
                 case "9.4.0":
                 case "9.4.5":
                 case "9.5.0":
+                case "9.5.0.nx":
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromRigidLink.cs:68]: Can we add a check here for XtoYY/ZZ, YtoXX,ZZ and ZtoXX/YY please and raise a warning if they are true. Something like:
```
LinkConstraint con = link.Constraint;
if(con.XtoYY || lcon.XtoZZ || con.YtoXX || lcon.YtoZZ || con.ZtoXX || lcon.ZtoYY)
    Engine.Base.RecordWarning("Imposed rotations due to translations are not supported in this Adapter.");
```

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
Tested using the test script provided, happy that `PointForce` and `AreaUniformlyDistributedLoad` can now push to NX (pull is unaffected as it's just an extra , on the end. 

One minor change to raise about `RigidLink` as they are not fully supported.

**Review by EmmaSander — COMMENTED** [review]
Not completed yet. Update to create load combination to be added as well, new format needed for NX.

**Review by peterjamesnugent — APPROVED** [review]
Changes addressed and works well.

There are some bugs relating to using multiple push components with `FEMesh` and `BarVaryingLoad` that will be picked up in a new PR.

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge
