### PR TITLE
Fixed bug where SaveAs command caused an error

### LINKED ISSUE #289: Bug with SaveAs command in Midas
#### Description:

There is an issue with the 'SaveAs' command when the midas file is not a empty file. Please see below for the error message.
image

#### Test file(s):

Please use the test script below and run the execute workflow
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=bdWLDi&cid=c70586d3%2Df382%2D473f%2Dab89%2Db962fae9a4aa&RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FMidasCivil%5FToolkit%2F%23289%2DSaveAsNotWorking&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

### PR DESCRIPTION
**Pull request by KalleEdstroem**
The copying of the `.mcb` and `.mct` file when using the `SaveAs` command did not work. It used the wrong input for the `File.Copy(string, string)`. The second string pointed to a `directory` rather than a `destination file`.

This made it so the `.mcb` and `.mct` file was not copied.
The issue also resulted in the issue stated in #289 which this closes.
   
### Issues addressed by this PR

Closes #289 

### Test files

Please use the test script below and run the execute workflow.
Before testing
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=bdWLDi&cid=c70586d3%2Df382%2D473f%2Dab89%2Db962fae9a4aa&RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FMidasCivil%5FToolkit%2F%23289%2DSaveAsNotWorking&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

### CODE REVIEW

File: MidasCivil_Adapter/AdapterActions/Execute.cs [hunk 1]
```diff
@@ -114,10 +114,10 @@ public bool RunCommand(SaveAs command)
             Directory.CreateDirectory(newDirectory);
             string[] mcbFiles = Directory.GetFiles(m_directory, "*.mcb");
             foreach (string mcbFile in mcbFiles)
-                File.Copy(mcbFile, newDirectory);
+                File.Copy(mcbFile, Path.Combine(newDirectory, command.FileName + ".mcb"));
```
Comment (peterjamesnugent) [inline MidasCivil_Adapter/AdapterActions/Execute.cs:117]: Can you store `command.FileName`, given that it accessed three times you may as well just store the `string` and the start of the method.

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
One minor comment about storing a value, otherwise functionality is there after testing the script.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
